### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by sandipan1** [nick-youngblut/pushmsg#1]
This is the error I get while running `pip install pushmsg`

`     ERROR: Command errored out with exit status 1:
     command: /home/sandipan/miniconda3/envs/myenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vga1wl73/pushmsg/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vga1wl73/pushmsg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vga1wl73/pushmsg/pip-egg-info
         cwd: /tmp/pip-install-vga1wl73/pushmsg/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vga1wl73/pushmsg/setup.py", line 3, in <module>
        import pushmsg
      File "/tmp/pip-install-vga1wl73/pushmsg/pushmsg/__init__.py", line 3, in <module>
        from pushmsg.pushmsg import *
      File "/tmp/pip-install-vga1wl73/pushmsg/pushmsg/pushmsg.py", line 22, in <module>
        from pushbullet import Pushbullet
    ModuleNotFoundError: No module named 'pushbullet'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

`

**Comment by nick-youngblut** [comment]
I'm guessing the error is due to you not having `pushbullet.py` installed. I've updated the README to clarify that this dependency is required
